version : "3.8"

services:
  java_app:
    container_name: java_app
    build:
      context: .
    networks:
      - exp-app
    depends_on:
      - mysql_db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql_db:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "springstudent"
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 60s
    ports:
      - "8081:8080"


  mysql_db:
    container_name: mysql
    image: mysql
    networks: 
      - exp-app
    environment:
      MYSQL_ROOT_PASSWORD: "springstudent"
      MYSQL_DATABASE: "expenses_tracker"
      MYSQL_USER: "springstudent"
      MYSQL_PASSWORD: "springstudent"
    restart: always
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost","-uspringstudent", "-pspringstudent"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./mysql-data:/var/lib/mysql
    
networks:
  exp-app:
